routes:
    
    # app

    - name: dummy.app.whoami
      methods: ["GET"]
      uri:
          pattern: whoami
          requirements: []
      controller: \Michcald\Dummy\App\Controller\AppController
      action: whoAmIAction
    
    - name: dummy.app.list
      methods: ["GET"]
      uri:
          pattern: app
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Administrable\AppController
      action: listAction
    
    - name: dummy.app.read
      methods: ["GET"]
      uri:
          pattern: app/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Administrable\AppController
      action: readAction

    - name: dummy.app.create
      methods: ["POST"]
      uri:
          pattern: app
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Administrable\AppController
      action: createAction

    - name: dummy.app.update
      methods: ["PUT"]
      uri:
          pattern: app/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Administrable\AppController
      action: updateAction

    - name: dummy.app.delete
      methods: ["DELETE"]
      uri:
          pattern: app/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Administrable\AppController
      action: deleteAction

    # app grant

    - name: dummy.grant.list
      methods: ["GET"]
      uri:
          pattern: grant
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Administrable\GrantController
      action: listAction
    
    - name: dummy.grant.read
      methods: ["GET"]
      uri:
          pattern: grant/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\Administrable\GrantController
      action: readAction

    - name: dummy.grant.update
      methods: ["PUT"]
      uri:
          pattern: grant/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\Administrable\GrantController
      action: updateAction
    
    # repository
    
    - name: dummy.repository.create
      methods: ["POST"]
      uri:
          pattern: repository
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Administrable\RepositoryController
      action: createAction
    
    - name: dummy.repository.read
      methods: ["GET"]
      uri:
          pattern: repository/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: readAction
    
    - name: dummy.repository.list
      methods: ["GET"]
      uri:
          pattern: repository
          requirements: []
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: listAction
      
    - name: dummy.repository.update
      methods: ["PUT"]
      uri:
          pattern: repository/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\Administrable\RepositoryController
      action: updateAction
      
    - name: dummy.repository.delete
      methods: ["DELETE"]
      uri:
          pattern: repository/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\Administrable\RepositoryController
      action: deleteAction

    # repository field
    
    - name: dummy.repository.field.create
      methods: ["POST"]
      uri:
          pattern: repository_field
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Repository\Administrable\FieldController
      action: createAction
    
    - name: dummy.repository.field.read
      methods: ["GET"]
      uri:
          pattern: repository_field/{id}
          requirements:
              - param: id
                value: \d+
      controller: \Michcald\Dummy\App\Controller\Repository\FieldController
      action: readAction
    
    - name: dummy.repository.field.list
      methods: ["GET"]
      uri:
          pattern: repository_field
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Repository\FieldController
      action: listAction
      
    - name: dummy.repository.field.update
      methods: ["PUT"]
      uri:
          pattern: repository_field/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Repository\Administrable\FieldController
      action: updateAction
      
    - name: dummy.repository.field.delete
      methods: ["DELETE"]
      uri:
          pattern: repository_field/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Repository\Administrable\FieldController
      action: deleteAction
    
    # entity
    
    - name: dummy.entity.list
      methods: ["GET"]
      uri:
          pattern: "_{repositoryName}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: listAction
    
    - name: dummy.entity.read
      methods: ["GET"]
      uri:
          pattern: "_{repositoryName}/{id}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: readAction

    - name: dummy.entity.create
      methods: ["POST"]
      uri:
          pattern: "_{repositoryName}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: createAction

    - name: dummy.entity.delete
      methods: ["DELETE"]
      uri:
          pattern: "_{repositoryName}/{id}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: deleteAction

    # default
    
    - name: dummy.not_found
      methods: ["GET","POST","PUT","DELETE","OPTIONS","PATCH","HEAD"]
      uri:
          pattern: "{any}"
          requirements:
              - param: any
                value: ".*"
      controller: \Michcald\Dummy\App\Controller\DummyController
      action: notFoundAction