routes:
    
    # app
    
    - name: dummy.app.list
      methods: ["GET"]
      uri:
          pattern: app
          requirements: []
      controller: \Michcald\Dummy\App\Controller\AppController
      action: listAction
    
    - name: dummy.app.read
      methods: ["GET"]
      uri:
          pattern: app/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\AppController
      action: readAction

    - name: dummy.app.create
      methods: ["POST"]
      uri:
          pattern: app
          requirements: []
      controller: \Michcald\Dummy\App\Controller\AppController
      action: createAction

    - name: dummy.app.delete
      methods: ["DELETE"]
      uri:
          pattern: app/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\AppController
      action: deleteAction
    
    # repository
    
    - name: dummy.repository.create
      methods: ["POST"]
      uri:
          pattern: repository
          requirements: []
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: createAction
    
    - name: dummy.repository.read
      methods: ["GET"]
      uri:
          pattern: repository/{name}
          requirements:
              - param: name
                value: "[a-z0-9_]+"
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: readAction
    
    - name: dummy.repository.list
      methods: ["GET"]
      uri:
          pattern: repository
          requirements: []
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: listAction
      
    - name: dummy.repository.update
      methods: ["PUT"]
      uri:
          pattern: repository/{name}
          requirements:
              - param: name
                value: "[a-z0-9_]+"
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: updateAction
      
    - name: dummy.repository.delete
      methods: ["DELETE"]
      uri:
          pattern: repository/{name}
          requirements:
              - param: name
                value: "[a-z0-9_]+"
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: deleteAction

    # repository
    
    - name: dummy.repository.field.create
      methods: ["POST"]
      uri:
          pattern: repository/field
          requirements: []
      controller: \Michcald\Dummy\App\Controller\Repository\FieldController
      action: createAction
    
    - name: dummy.repository.field.read
      methods: ["GET"]
      uri:
          pattern: repository/field/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Repository\FieldController
      action: readAction
    
    - name: dummy.repository.field.list
      methods: ["GET"]
      uri:
          pattern: repository/{repositoryId}/field
          requirements:
              - param: repositoryId
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\Repository\FieldController
      action: listAction
      
    - name: dummy.repository.field.update
      methods: ["PUT"]
      uri:
          pattern: repository/field/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: updateAction
      
    - name: dummy.repository.field.delete
      methods: ["DELETE"]
      uri:
          pattern: repository/field/{id}
          requirements:
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\RepositoryController
      action: deleteAction
    
    # entity
    
    - name: dummy.entity.list
      methods: ["GET"]
      uri:
          pattern: "_{repositoryName}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: listAction
    
    - name: dummy.entity.read
      methods: ["GET"]
      uri:
          pattern: "_{repositoryName}/{id}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: readAction

    - name: dummy.entity.create
      methods: ["POST"]
      uri:
          pattern: "_{repositoryName}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: createAction

    - name: dummy.entity.delete
      methods: ["DELETE"]
      uri:
          pattern: "_{repositoryName}/{id}"
          requirements:
              - param: repositoryName
                value: "[a-z0-9_]*"
              - param: id
                value: "\d+"
      controller: \Michcald\Dummy\App\Controller\EntityController
      action: deleteAction

    # default
    
    - name: dummy.not_found
      methods: ["GET","POST","PUT","DELETE","OPTIONS","PATCH","HEAD"]
      uri:
          pattern: "{any}"
          requirements:
              - param: any
                value: ".*"
      controller: \Michcald\Dummy\App\Controller\DummyController
      action: notFoundAction