repositories:
    - name: collection
      description: ~
      label:
          singular: Collezione
          plural: Collezioni
      parents: []
      children: [collection_item, collection_csv]
      showable: true 
      fields:
          - name: created
            type: date
            label: Data
            description: ~
            searchable: false
            sortable: true
            required: true
            main: false
            list: true
            validators: []
          - name: title
            type: string
            label: Titolo
            description: ~
            searchable: true
            sortable: false
            required: false
            main: true
            list: true
            validators: []
          - name: is_public
            type: boolean
            label: Pubblico
            description: Mostrato sul sito
            searchable: false
            sortable: false
            required: true
            main: false
            list: true
            validators: []

    - name: collection_csv
      description: Struttura del CSV: codice,interno della scarpa,materiale,colore.<br />Attenzione: Il file non deve avere la riga di intestazione
      label:
          singular: CSV Articoli
          plural: CSV Articoli
      parents: [collection]
      children: []
      showable: true 
      fields:
          - name: file
            type: file
            label: File CSV
            description: ~
            searchable: false
            sortable: false
            required: true
            main: true
            list: true
            validators: []

    - name: collection_item
      description: ~
      label:
          singular: Articolo
          plural: Articoli
      parents: [collection]
      children: [collection_item_img]
      showable: true 
      fields:
          - name: code
            type: string
            label: Codice
            description: ~
            searchable: true
            sortable: true
            required: true
            main: true
            list: true
            validators: []
          - name: inside
            type: string
            label: Interno della scarpa
            description: ~
            searchable: false
            sortable: true
            required: false
            main: false
            list: true
            validators: []
          - name: material
            type: string
            label: Materiale
            description: ~
            searchable: true
            sortable: false
            required: false
            main: false
            list: true
            validators: []
          - name: color
            type: string
            label: Colore
            description: ~
            searchable: true
            sortable: true
            required: false
            main: false
            list: true
            validators: []

    - name: collection_item_img
      description: ~
      label:
          singular: Immagine
          plural: Immagini
      parents: [collection_item]
      children: []
      showable: false 
      fields:
          - name: img
            type: file
            label: Immagine
            description: ~
            searchable: false
            sortable: false
            required: true
            main: true
            list: true
            validators: []