repositories:
    - name: event
      description: ~
      label:
          singular: Evento
          plural: Eventi
      parents: []
      children: [event_img]
      showable: true 
      fields:
          - name: date
            type: date
            label: Data
            description: ~
            searchable: true
            sortable: false
            required: true
            main: true
            list: true
            validators: []
          - name: text_it
            type: text
            label: Testo ita
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: true
            validators: []
          - name: text_en
            type: text
            label: Testo eng
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_ge
            type: text
            label: Testo ger
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_es
            type: text
            label: Testo spa
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_fr
            type: text
            label: Testo fra
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: video
            type: text
            label: Video
            description: Copia/Incolla codice embed
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []