repositories:
    - name: event_img
      description: ~
      label:
          singular: Immagine Evento
          plural: Immagini Eventi
      parents: [event]
      children: []
      showable: false 
      fields:
          - name: img
            type: file
            label: Immagine
            description: ~
            searchable: false
            sortable: false
            required: true
            main: false
            list: true
            validators: []
          - name: display_order
            type: integer
            label: Ordine di visualizzazione
            description: ~
            searchable: false
            sortable: true
            required: false
            main: false
            list: true
            validators: []