repositories:
    - name: image
      description: ~
      label:
          singular: Azienda
          plural: Azienda
      parents: []
      children: []
      showable: true 
      fields:
          - name: title
            type: string
            label: Titolo
            description: ~
            searchable: true
            sortable: false
            required: false
            main: true
            list: true
            validators: []
          - name: img
            type: file
            label: Immagine
            description: ~
            searchable: false
            sortable: false
            required: true
            main: false
            list: true
            validators: []
          - name: display_order
            type: integer
            label: Ordine di visualizzazione
            description: ~
            searchable: false
            sortable: true
            required: false
            main: false
            list: true
            validators: []