repositories:
    - name: marketing
      description: ~
      label:
          singular: Marketing
          plural: Marketing
      parents: []
      children: [marketing_img]
      showable: true 
      fields:
          - name: text_it
            type: text
            label: Testo ita
            description: ~
            searchable: true
            sortable: false
            required: true
            main: true
            list: true
            validators: []
          - name: text_en
            type: text
            label: Testo eng
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_ge
            type: text
            label: Testo ger
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_es
            type: text
            label: Testo spa
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: text_fr
            type: text
            label: Testo fra
            description: ~
            searchable: true
            sortable: false
            required: true
            main: false
            list: false
            validators: []
          - name: display_order
            type: integer
            label: Ordine di visualizzazione
            description: ~
            searchable: false
            sortable: true
            required: false
            main: false
            list: true
            validators: []