repositories:
    - name: post_category
      description: Questa e' la descrizione
      label:
          singular: Category
          plural: Categories
      parents: []
      children: [post]
      fields:
          - name: name
            type: string
            label: Category name
            description: Category name descr
            searchable: true
            sortable: true
            required: true
            main: true
            list: true
            validators: []
          - name: description
            type: text
            label: Category descr
            description: Category descr descr
            searchable: true
            sortable: false
            required: false
            main: false
            list: true
            validators: []