repositories:
    - name: shop
      description: ~
      label:
          singular: Negozio
          plural: Negozi
      parents: []
      children: []
      showable: true 
      fields:
          - name: name
            type: string
            label: Nome
            description: ~
            searchable: true
            sortable: true
            required: true
            main: true
            list: true
            validators: []
          - name: description
            type: text
            label: Descrizione
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: location
            type: string
            label: Localita'
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: postcode
            type: string
            label: CAP
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: address
            type: string
            label: Via
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: country
            type: string
            label: Paese (Nazione)
            description: ~
            searchable: true
            sortable: true
            required: false
            main: false
            list: true
            validators: []
          - name: latitude
            type: string
            label: Latitudine
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: longitude
            type: string
            label: Longitudine
            description: ~
            searchable: false
            sortable: false
            required: false
            main: false
            list: false
            validators: []
          - name: display_order
            type: integer
            label: Ordine di visualizzazione
            description: ~
            searchable: false
            sortable: true
            required: false
            main: false
            list: true
            validators: []

    - name: shop_csv
      description: Struttura del CSV: nome,localita,cap,via,paese.<br />Attenzione: Il file non deve avere la riga di intestazione
      label:
          singular: CSV Negozi
          plural: CSV Negozi
      parents: []
      children: []
      showable: true 
      fields:
          - name: file
            type: file
            label: File CSV
            description: ~
            searchable: false
            sortable: false
            required: true
            main: true
            list: true
            validators: []